name: Run TODO to Issue

on:
  workflow_dispatch:


jobs:
  todo:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force git history for full scan
        run: |
          git fetch --unshallow || true
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      
      - name: List TODOs for debug
        run: |
          grep -rIn --include=\*.cs "TODO" . || echo "No TODOs found"

      - name: Run TODO to Issue Action
        uses: alstr/todo-to-issue-action@v5
        with:
          INSERT_ISSUE_URLS: true

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi
